Sneat.MVC/Models/DTO/Project/ProjectInputModel.cs
using Sneat.MVC.Common;
using System;
using System.Collections.Generic;

namespace Sneat.MVC.Models.DTO.Project
{
    public class ProjectInputModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public int PMId { get; set; }
        public List<int> UserIds { get; set; }
        public List<int> TeamIds { get; set; }
    }

    public class ProjectUserModel
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserAvatar { get; set; }
    }

    public class ProjectOutputModel : ProjectInputModel
    {
        public int ID { get; set; }
        public int? Status { get; set; }
        public List<ProjectUserModel> ListUsers { get; set; }
        public string StatusStr 
        {
            get
            {
                switch (Status)
                {
                    case SystemParam.ACTIVE:
                        return SystemParam.STATUS_ACTIVE_STR;
                    case SystemParam.IN_ACTIVE:
                        return SystemParam.STATUS_IN_ACTIVE_STR;
                    default:
                        return "Unknown status"; 
                }
            }
        }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }

}

Sneat.MVC/Models/Entity/Project.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Sneat.MVC.Models.Enum;
using System;
using System.Collections.Generic;

namespace Sneat.MVC.Models.Entity
{
    public class Project
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int IsDeleted { get; set; }
        public Status? Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string TeamIds { get; set; }
        public virtual ICollection<UserProject> UserProjects { get; set; }
    }
}

Sneat.MVC/Controllers/API/ProjectController.cs
using Sneat.MVC.Common;
using Sneat.MVC.Models.APIModel;
using Sneat.MVC.Models.DTO.Project;
using Sneat.MVC.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;

namespace Sneat.MVC.Controllers.API
{
    public class ProjectController : ApiController
    {
        private readonly ProjectService _projectService;
        private readonly AuthenticationService _authenticationService;

        public ProjectController()
        {
            _projectService = new ProjectService();
            _authenticationService = new AuthenticationService();
        }

        [HttpGet]
        public async Task<JsonResultModel> GetListProject(
            int page = SystemParam.PAGE_DEFAULT, 
            int limit = SystemParam.MAX_ROW_IN_LIST_WEB, 
            string search = "")
        {
            return await _projectService.GetListProject(page, limit, search);
        }

        [HttpPost]
        public async Task<JsonResultModel> CreateProject(ProjectInputModel input)
        {
            var token = Utils.getTokenApp(Request.Headers);
            var userID = await _authenticationService.GetUserLoginID(token);
            if (userID > SystemParam.RETURN_FALSE)
                input.PMId = userID;
            var result = await _projectService.CreateProject(input);

            if (result == SystemParam.EXISTED_PROJECT_NAME_ERR)
                return JsonResponse.ErrorResult(SystemParam.EXISTED_PROJECT_NAME_ERR_STR, SystemParam.SERVER_ERROR_CODE);
            else if (result == SystemParam.RETURN_TRUE)
                return JsonResponse.Success(SystemParam.MESSAGE_SUCCESS, result);
            else
                return JsonResponse.ServerError();

        }

        [HttpPost]
        public async Task<JsonResultModel> UpdateProject(ProjectOutputModel input)
        {
            var result = await _projectService.UpdateProject(input);

            if (result == SystemParam.EXISTED_PROJECT_NAME_ERR)
                return JsonResponse.ErrorResult(SystemParam.EXISTED_PROJECT_NAME_ERR_STR, SystemParam.SERVER_ERROR_CODE);
            else if (result == SystemParam.PROJECT_NOT_FOUND_ERR)
                return JsonResponse.ErrorResult(SystemParam.PROJECT_NOT_FOUND_ERR_STR, SystemParam.SERVER_ERROR_CODE);
            else if (result == SystemParam.RETURN_TRUE)
                return JsonResponse.Success(SystemParam.MESSAGE_SUCCESS, result);
            else
                return JsonResponse.ServerError();
        }

        [HttpGet]
        public JsonResultModel ProjectDetail(int ID)
        {
            var result = _projectService.DetailProject(ID);
            return JsonResponse.Success(SystemParam.MESSAGE_SUCCESS, result);
        }

        [HttpGet]
        public JsonResultModel ListUserProject(int projectID)
        {
            var result = _projectService.GetListUserProject(projectID);
            return JsonResponse.Success(SystemParam.MESSAGE_SUCCESS, result);
        }

        [HttpPost]
        public async Task<JsonResultModel> RemoveProject(int ID)
        {
            var result = await _projectService.RemoveProject(ID);
            if (result == SystemParam.PROJECT_NOT_FOUND_ERR)
                return JsonResponse.ErrorResult(SystemParam.PROJECT_NOT_FOUND_ERR_STR, SystemParam.SERVER_ERROR_CODE);
            else if (result == SystemParam.RETURN_TRUE)
                return JsonResponse.Success(SystemParam.MESSAGE_SUCCESS, result);
            else
                return JsonResponse.ServerError();
        }

        #region Personal Project management
        [HttpGet]
        public async Task<JsonResultModel> PersonalProjects()
        {
            var token = Utils.getTokenApp(Request.Headers);
            var userID = await _authenticationService.GetUserLoginID(token);
            var result = new List<ProjectOutputModel>();
            if (userID > SystemParam.RETURN_FALSE)
                result = await _projectService.PersonalProjects(userID);

            return JsonResponse.Success(SystemParam.MESSAGE_SUCCESS, result);
        }

        #endregion
    }
}

Sneat.MVC/Controllers/ProjectsController.cs
using Sneat.MVC.App_Start;
using Sneat.MVC.Common;
using Sneat.MVC.Models.DTO.Project;
using Sneat.MVC.Models.DTO.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Sneat.MVC.Controllers
{
    public class ProjectsController : BaseController
    {
        #region Project management
        [UserAuthenticationFilter]
        public ActionResult Index()
        {
            return View();
        }

        [UserAuthenticationFilter]
        public async Task<PartialViewResult> Search(int page, string search = "")
        {
            var result = await _projectService.SearchProject(page, SystemParam.MAX_ROW_IN_LIST_WEB, search);
            return PartialView("_ListProject", result);
        }

        [UserAuthenticationFilter]
        public async Task<ActionResult> Create()
        {
            ViewBag.ListTeam = await _teamService.GetListTeam();
            return View();
        }

        [HttpPost]
        public async Task<int> CreateProject(ProjectInputModel input)
        {
            UserDetailOutputModel userLogin = UserLogins;
            input.PMId = userLogin.ID;
            return await _projectService.CreateProject(input);
        }

        [UserAuthenticationFilter]
        public async Task<ActionResult> Update(int ID)
        {
            ViewBag.ListTeam = await _teamService.GetListTeam();
            var detail = _projectService.DetailProject(ID);
            return View(detail);
        }

        [UserAuthenticationFilter]
        public ActionResult ProjectDetail(int projectID)
        {
            var detail = _projectService.DetailProject(projectID);
            ViewBag.ListUserProject = _projectService.GetListUserProject(projectID);
            return View(detail);
        }

        [HttpPost]
        public async Task<int> RemoveProject(int ID)
        {
            return await _projectService.RemoveProject(ID);
        }

        [HttpPost]
        public async Task<int> UpdateProject(ProjectOutputModel input)
        {
            return await _projectService.UpdateProject(input);
        }

        [UserAuthenticationFilter]
        public PartialViewResult SearchUserProject(int page, int projectID, int limit = SystemParam.MAX_ROW_IN_LIST_WEB, string search = "")
        {
            var result = _projectService.SearchUserProject(page, limit, projectID, search);
            return PartialView("_ListUserProject", result);
        }

        [UserAuthenticationFilter]
        public async Task<int> AddUserProject(List<int> userIds, int projectID)
        {
            return await _projectService.AddUserProject(userIds, projectID);
        }
       
        [HttpPost]
        public async Task<JsonResult> ListUserByTeam(List<int> teamIds)
        {
            var listSPs = await _teamService.ListUserByTeam(teamIds);
            return Json(listSPs, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Personal Project management
        [UserAuthenticationFilter]
        public async Task<ActionResult> PersonalProjects()
        {
            UserDetailOutputModel userLogin = UserLogins;
            var listProject = await _projectService.PersonalProjects(userLogin.ID);
            return View(listProject);
        }

        [UserAuthenticationFilter]
        public PartialViewResult SearchUserProjectDetail(int page, int projectID, int limit = SystemParam.MAX_ROW_IN_LIST_WEB, string search = "")
        {
            var result = _projectService.SearchUserProject(page, limit, projectID, search);
            return PartialView("_ListUserProjectDetail", result);
        }

        [UserAuthenticationFilter]
        public PartialViewResult ProjectOverview(int projectID)
        {
            var detail = _projectService.DetailProject(projectID);
            return PartialView("_ProjectOverview", detail);
        }
        #endregion
    }
}

Sneat.MVC/Controllers/WorkPackageController.cs
using Sneat.MVC.App_Start;
using Sneat.MVC.Common;
using Sneat.MVC.Models.DTO.User;
using Sneat.MVC.Models.DTO.WorkPackage;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Sneat.MVC.Controllers
{
    public class WorkPackageController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        [UserAuthenticationFilter]
        public async Task<PartialViewResult> SearchWorkPackage(
            int page = SystemParam.PAGE_DEFAULT, 
            int limit = SystemParam.MAX_ROW_IN_LIST_WEB, 
            string search = "",
            int? projectID = null,
            int? priorityType = null
            )
        {
            ViewBag.ListUserProject = _projectService.GetListUserProject((int)projectID);
            var result = await _workPackageService.SearchWorkPackage(page, limit, search, projectID, priorityType);  
            return PartialView("_ListWorkPackage", result);
        }

        [HttpPost]
        public async Task<int> CreateWorkPackage(WorkPackageInputModel input)
        {
            UserDetailOutputModel userLogin = UserLogins;
            input.AssignorID = userLogin.ID;
            return await _workPackageService.CreateWorkPackage(input);
        }

        public async Task<JsonResult> DetailWorkPackage(int ID)
        {
            var result = await _workPackageService.DetailWorkPackage(ID);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<int> UpdateWorkPackage(WorkPackageOutputModel input)
        {
            return await _workPackageService.UpdateWorkPackage(input);
        }
    }
}

Sneat.MVC/Views/Projects/Index.cshtml
@{
    Layout = "~/Views/Shared/_SneatProLayout.cshtml";
    ViewData["title"] = "Project management";
}
@using Sneat.MVC.Models.DTO.User
@using Sneat.MVC.Common
@{ UserDetailOutputModel ss = (UserDetailOutputModel)HttpContext.Current.Session[SystemParam.SESSION_LOGIN];
    if (ss == null)
    {
        Response.Redirect("/Home/Login");
    }
}

<div class="content-wrapper">
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="py-3 mb-4"><span class="text-muted fw-light" @*data-i18n="User"*@>Quản lý dự án /</span> Dự án</h4>


    <div class="card mb-4">
        <h5 class="card-header" @*data-i18n="User"*@>Danh sách dự án</h5>
        <div class="row mb-2  px-md-4 px-2">
            <div class="col-md-4 offset-md-0">
                <div class="input-group input-group-merge">
                    <span class="input-group-text" id="basic-addon-search31"><i class="bx bx-search"></i></span>
                    <input type="text" class="form-control " id="txt-key-search" placeholder="Tên dự án" onchange="searchProject()" />
                </div>
            </div>

        </div>
        <div class="row mb-2 px-md-4 px-2">
            <div class="col-md-12 mb-2">
                @* @if (ss.PermissionTabs.Contains("createRoleTab"))
        {

        }*@
               
                <a title="Thêm dự án" style="float: right" class="btn btn-primary" href="/Projects/Create">
                    <i class='menu-icon tf-icons bx bx-plus'></i>
                    Thêm mới
                </a>
                @*<button class="btn btn-primary" id="shepherd-example">Start tour</button>*@
            </div>
        </div>

        @*  @if (ss.PermissionTabs.Contains("viewRoleTab"))
        {

        }*@
        <div class=" table-responsive px-md-4 px-2" id="list_project">
            @{ Html.RenderAction("Search", "Projects", new { Page = 1, search = "" }); }
        </div>
    </div>

    </div>

    <div class="content-backdrop fade"></div>
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
@Scripts.Render("~/Scripts/ScriptModel/project-script.js")

Sneat.MVC/Views/Projects/ProjectDetail.cshtml
@{
    Layout = "~/Views/Shared/_SneatProLayout.cshtml";
    ViewData["title"] = "Project detail";
}
@using Sneat.MVC.Models.DTO.User
@using Sneat.MVC.Models.DTO.Project;
@using Sneat.MVC.Common
@model ProjectOutputModel
@{ UserDetailOutputModel ss = (UserDetailOutputModel)HttpContext.Current.Session[SystemParam.SESSION_LOGIN];
    if (ss == null)
    {
        Response.Redirect("/Home/Login");
    }
}

<div class="content-wrapper">
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="py-3 mb-4"><span class="text-muted fw-light" @*data-i18n="User"*@>Quản lý dự án / Dự án của tôi /</span>  @Model.Name</h4>

        <div class="row mb-3">
            <div class="col-md-12 col-xs-12">
                <div class="mt-1 mb-1 pull-right pr-10 pb-10">

                    <div class="btn-group" style="float: right;">
                        <button type="button"
                                class="btn btn-label-primary dropdown-toggle"
                                data-bs-toggle="dropdown"
                                aria-expanded="false">
                            Tùy chọn
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="javascript:void(0);" onclick="projectOverview(@Model.ID);">Tổng quan</a></li>
                            <li><a class="dropdown-item" href="javascript:void(0);">Another action</a></li>
                            <li><a class="dropdown-item" href="javascript:void(0);">Something else here</a></li>
                            <li>
                                <hr class="dropdown-divider" />
                            </li>
                            <li><a class="dropdown-item" href="javascript:void(0);">Separated link</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div id="project-overview-container" class="mb-3">
            @{ Html.RenderAction("ProjectOverview", "Projects", new { projectID = Model.ID }); }
        </div>

        <div id="project-task-container">
            <div class="card mb-4">
                <div class="card-header">
                    <h5 class="card-title mb-0">Nhiệm vụ</h5>
                </div>
                <div class="card-body">
                    <div class="row mb-2 px-md-4 px-2">
                        <div class="col-md-4 offset-md-0">
                            <div class="input-group input-group-merge">
                                <span class="input-group-text" id="basic-addon-search31"><i class="bx bx-search"></i></span>
                                <input type="text" class="form-control " id="txt-key-search-task" placeholder="Tiêu đề, tên, email thành viên" onchange="searchWorkPackageProject(@Model.ID)" />
                            </div>
                        </div>
                        <div class="col-md-4 offset-md-0">
                            <select id="slPriority" class="selectpicker w-100" data-style="btn-default" onchange="searchWorkPackageProject(@Model.ID)">
                                <option value="">-- Chọn độ ưu tiên --</option>
                                <option value="@SystemParam.PRIORITY_TYPE_HOT_FIX">@SystemParam.PRIORITY_TYPE_HOT_FIX_STR</option>
                                <option value="@SystemParam.PRIORITY_TYPE_IMMEDIATE">@SystemParam.PRIORITY_TYPE_IMMEDIATE_STR</option>
                                <option value="@SystemParam.PRIORITY_TYPE_HIGH">@SystemParam.PRIORITY_TYPE_HIGH_STR</option>
                                <option value="@SystemParam.PRIORITY_TYPE_NORMAL">@SystemParam.PRIORITY_TYPE_NORMAL_STR</option>
                                <option value="@SystemParam.PRIORITY_TYPE_LOW">@SystemParam.PRIORITY_TYPE_LOW_STR</option>

                            </select>
                        </div>
                        <div class="col-md-4 offset-md-0">
                            <select id="slUserProject" class="select2 form-select" onchange="testmultiple()" multiple>
                                <option value="">-- Chọn thành viên --</option>
                                @foreach (var mem in ViewBag.ListUserProject)
                                {
                                    <option value="@mem.ID">@mem.UserName</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="row mb-2 mt-2 px-md-4 px-2">
                        <div class="col-md-12 mb-2">
                            <button class="btn btn-primary"
                                    type="button"
                                    style="float: right"
                                    data-bs-toggle="offcanvas"
                                    data-bs-target="#offcanvasAddTask"
                                    aria-controls="offcanvasAddTask">
                                <i class='menu-icon tf-icons bx bx-plus'></i>
                                Thêm mới nhiệm vụ
                            </button>
                        </div>

                    </div>
                    <div class=" table-responsive px-md-4 px-2" id="list_work_package_project">
                        @{ Html.RenderAction("SearchWorkPackage", "WorkPackage", new { Page = 1, search = "", projectID = Model.ID }); }
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<!-- Offcanvas to add new task -->
<div class="offcanvas offcanvas-end"
     tabindex="-1"
     data-bs-scroll="true"
     id="offcanvasAddTask"
     aria-labelledby="offcanvasAddUserLabel">
    <div class="offcanvas-header">
        <h5 id="offcanvasAddUserLabel" class="offcanvas-title">Nhiệm vụ mới</h5>
        <button type="button"
                class="btn-close text-reset"
                data-bs-dismiss="offcanvas"
                aria-label="Close"></button>
    </div>
    <div class="offcanvas-body mx-0 flex-grow-0">
        <div class="add-new-user pt-0" id="addNewUserForm">
            <input type="hidden" value="@Model.ID" id="task-add-project-id"/>
            <div class="mb-3">
                <label class="form-label" for="add-user-fullname">Tiêu đề</label>
                <input type="text"
                       class="form-control"
                       id="add-task-subject"
                       placeholder="Nhập tiêu đề ..."
                       name="userFullname"
                       aria-label="John Doe" />
            </div>
            <div class="mb-3">
                <label class="form-label" for="add-user-email">Mô tả</label>
                <div class="form-control p-0 pt-1">
                    <div class="comment-toolbar border-0 border-bottom">
                        <div class="d-flex justify-content-start">
                            <span class="ql-formats me-0">
                                <button class="ql-bold"></button>
                                <button class="ql-italic"></button>
                                <button class="ql-underline"></button>
                                <button class="ql-list" value="ordered"></button>
                                <button class="ql-list" value="bullet"></button>
                                <button class="ql-link"></button>
                                <button class="ql-image"></button>
                            </span>
                        </div>
                    </div>
                    <div class="comment-editor border-0 pb-4" id="add-task-description"></div>
                </div>
            </div>
            <div class="mb-3">
                <label class="form-label" for="country">Thành viên bàn giao</label>
                <select id="add-assignee" class="select2 form-select">
                    <option value="">-- Chọn thành viên --</option>
                    @foreach (var mem in ViewBag.ListUserProject)
                    {
                        <option value="@mem.ID">@mem.UserName</option>
                    }

                </select>
            </div>
            <div class="mb-3">
                <label class="form-label" for="add-user-contact">Thời gian dự kiến (h)</label>
                <input type="number"
                       id="add-est-time"
                       class="form-control phone-mask"
                       placeholder="Nhập thời gian dự kiến..."
                       aria-label="john.doe@example.com"
                       name="userContact" />
            </div>
            <div class="mb-3">
                <label class="form-label" for="add-user-contact">Thời gian thực tế (h)</label>
                <input type="number"
                       id="add-real-time"
                       class="form-control phone-mask"
                       placeholder="Nhập thời gian thực tế..."
                       aria-label="john.doe@example.com"
                       name="userContact" />
            </div>
            <div class="mb-3">
                <label class="form-label" for="add-user-contact">Thời gian còn lại (h)</label>
                <input type="number"
                       id="add-left-time"
                       class="form-control phone-mask"
                       placeholder="Nhập thời gian còn lại..."
                       aria-label="john.doe@example.com"
                       name="userContact" />
            </div>
            <div class="mb-3">
                <label class="form-label" for="country">Độ ưu tiên</label>
                <select id="add-priority-point" class="select2 form-select">
                    <option value="">-- Chọn độ ưu tiên --</option>
                    <option value="@SystemParam.PRIORITY_TYPE_HOT_FIX">@SystemParam.PRIORITY_TYPE_HOT_FIX_STR</option>
                    <option value="@SystemParam.PRIORITY_TYPE_IMMEDIATE">@SystemParam.PRIORITY_TYPE_IMMEDIATE_STR</option>
                    <option value="@SystemParam.PRIORITY_TYPE_HIGH">@SystemParam.PRIORITY_TYPE_HIGH_STR</option>
                    <option value="@SystemParam.PRIORITY_TYPE_NORMAL">@SystemParam.PRIORITY_TYPE_NORMAL_STR</option>
                    <option value="@SystemParam.PRIORITY_TYPE_LOW">@SystemParam.PRIORITY_TYPE_LOW_STR</option>

                </select>
            </div>
            <div class="mb-3">
                <label class="form-label" for="add-start-date">Ngày bắt đầu</label>
                <input type="text" class="form-control" placeholder="YYYY-MM-DD" id="flatpickr-start-date" />
            </div>
            <div class="mb-3">
                <label class="form-label" for="add-end-date">Ngày kết thúc</label>
                <input type="text" class="form-control" placeholder="YYYY-MM-DD" id="flatpickr-end-date" />
            </div>
            <button type="submit" class="btn btn-primary me-sm-3 me-1 " onclick="saveCreateWorkPackage()">Lưu</button>
            <button type="reset" class="btn btn-label-secondary" data-bs-dismiss="offcanvas">Đóng</button>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Content/sneat-admin-pro/vendor/libs/quill/katex.js"></script>
<script src="~/Content/sneat-admin-pro/vendor/libs/quill/quill.js"></script>
<script src="~/Scripts/ScriptModel/work-package-script.js"></script>

@Scripts.Render("~/Content/multiselect-dropdown/virtual-select.min.js")
<script>
    function projectOverview(projectID) {
        window.location.assign("/Projects/ProjectDetail?projectID=" + projectID);
    }

    function testmultiple() {
        var slUserProject = $('#slUserProject').val();
        var intArray = slUserProject.map(Number); // Convert each element to an integer
        console.log(intArray);
    }

</script>

Sneat.MVC/Views/Projects/_ProjectOverview.cshtml
@using Sneat.MVC.Models.DTO.User
@using Sneat.MVC.Models.DTO.Project;
@using Sneat.MVC.Common
@model ProjectOutputModel
@{ UserDetailOutputModel ss = (UserDetailOutputModel)HttpContext.Current.Session[SystemParam.SESSION_LOGIN];
    if (ss == null)
    {
        Response.Redirect("/Home/Login");
    }
}

<div class="row mb-3">
    <div class="col-12 col-lg-6">
        <div class="card mb-4">
            <h5 class="card-header" @*data-i18n="User"*@>Mô tả dự án</h5>
            <div class="card-body">
                <div class="col-md col-12 mb-md-0 mb-2">
                    <i>@Html.Raw(HttpUtility.HtmlDecode(Model.Description))</i>
                </div>

            </div>

        </div>
    </div>
    <div class="col-12 col-lg-6">
        <div class="card mb-4">
            <h5 class="card-header" @*data-i18n="User"*@>Trạng thái hoạt động</h5>
            <div class="card-body">
                <div class="col-md col-12 mb-md-0 mb-2">
                    @if (Model.Status == SystemParam.ACTIVE)
                    {
                        <span class="badge bg-label-success me-1">@Model.StatusStr</span>
                    }
                    else if (Model.Status == SystemParam.IN_ACTIVE)
                    {
                        <span class="badge bg-label-danger me-1">@Model.StatusStr</span>
                    }
                </div>

            </div>

        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6 col-lg-12 mb-md-0 mb-4">
        <div class="card h-100">
            <div class="card-header d-flex align-items-center justify-content-between">
                <h5 class="card-title m-0 me-2">Thành viên</h5>
                <div class="dropdown">
                    <button class="btn p-0"
                            type="button"
                            id="teamMemberList"
                            data-bs-toggle="dropdown"
                            aria-haspopup="true"
                            aria-expanded="false">
                        <i class="bx bx-dots-vertical-rounded"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="teamMemberList">
                        <a class="dropdown-item" href="javascript:void(0);">Select All</a>
                        <a class="dropdown-item" href="javascript:void(0);">Refresh</a>
                        <a class="dropdown-item" href="javascript:void(0);">Share</a>
                    </div>
                </div>
            </div>
            <div class="table-responsive" id="list_user_project_detail">
                @{ Html.RenderAction("SearchUserProjectDetail", "Projects", new { Page = 1, projectID = Model.ID, search = "" }); }

            </div>
        </div>
    </div>
</div>