Sneat.MVC/Models/DTO/Role/RoleOutputModel.cs
using System;
using System.Collections.Generic;

namespace Sneat.MVC.Models.DTO.Role
{
    public class RoleOutputModel : RoleInputModel
    {
        public int ID { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public List<UserRoleOutputModel> UserRoles { get; set; }
    }

    public class RoleInputModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public List<int> PermissionIDs { get; set; }

    }

    public class UserRoleOutputModel
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserAvatar { get; set; }
    }
}

Sneat.MVC/Models/Entity/Role.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace Sneat.MVC.Models.Entity
{
    public class Role
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int IsDeleted { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<RolePermission> RolePermissions { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}

Sneat.MVC/Controllers/API/RoleController.cs
using Sneat.MVC.Common;
using Sneat.MVC.Models.APIModel;
using Sneat.MVC.Models.DTO.Role;
using Sneat.MVC.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;

namespace Sneat.MVC.Controllers.API
{
    public class RoleController : ApiController
    {
        private readonly RoleService _roleService;
        public RoleController()
        {
            _roleService = new RoleService();
        }

        [HttpGet]
        public async Task<JsonResultModel> GetListRoles(
            int page = SystemParam.PAGE_DEFAULT,
            int limit = SystemParam.MAX_ROW_IN_LIST_WEB,
            string search = null)
        {
            var list =  await _roleService.SearchRole(page, limit, search);
            var paging = new PagingModel
            {
                Page = page,
                Limit = limit,
                TotalItemCount = list.TotalItemCount,
            };

            return JsonResponse.SucessPaging(list, paging);
        }

        [HttpPost]
        public async Task<JsonResultModel> CreateRole(RoleInputModel input)
        {
            var result = await _roleService.CreateRole(input);

            if (result == SystemParam.EXISTED_ROLE_NAME_ERR)
                return JsonResponse.ErrorResult(SystemParam.EXISTED_ROLE_NAME_ERR_STR, SystemParam.SERVER_ERROR_CODE);
            else if (result == SystemParam.RETURN_TRUE)
                return JsonResponse.Success(SystemParam.MESSAGE_SUCCESS, result);
            else
                return JsonResponse.ServerError();
        }

        [HttpPost]
        public async Task<JsonResultModel> UpdateRole(RoleOutputModel input)
        {
            var result = await _roleService.UpdateRole(input);

            if (result == SystemParam.EXISTED_ROLE_NAME_ERR)
                return JsonResponse.ErrorResult(SystemParam.EXISTED_ROLE_NAME_ERR_STR, SystemParam.SERVER_ERROR_CODE);
            else if (result == SystemParam.ROLE_NOT_FOUND_ERR)
                return JsonResponse.ErrorResult(SystemParam.ROLE_NOT_FOUND_ERR_STR, SystemParam.SERVER_ERROR_CODE);
            else if (result == SystemParam.RETURN_TRUE)
                return JsonResponse.Success(SystemParam.MESSAGE_SUCCESS, result);
            else
                return JsonResponse.ServerError();
        }

        [HttpGet]
        public async Task<JsonResultModel> DetailRole(int ID)
        {
            var result = await _roleService.DetailRole(ID);
            return JsonResponse.Success(SystemParam.MESSAGE_SUCCESS, result);
        }

        [HttpPost]
        public async Task<JsonResultModel> RemoveRole(int ID)
        {
            var result = await _roleService.RemoveRole(ID);
            if (result == SystemParam.ROLE_NOT_FOUND_ERR)
                return JsonResponse.ErrorResult(SystemParam.ROLE_NOT_FOUND_ERR_STR, SystemParam.SERVER_ERROR_CODE);
            else if (result == SystemParam.RETURN_TRUE)
                return JsonResponse.Success(SystemParam.MESSAGE_SUCCESS, result);
            else
                return JsonResponse.ServerError();
        }

        [HttpGet]
        public async Task<JsonResultModel> GetAllPermission()
        {
            var result = await _roleService.GetAllPermissions();
            return JsonResponse.Success(SystemParam.MESSAGE_SUCCESS, result);
        }
    }
}

Sneat.MVC/Controllers/RolesController.cs
using Sneat.MVC.App_Start;
using Sneat.MVC.Common;
using Sneat.MVC.Models.DTO.Permission;
using Sneat.MVC.Models.DTO.Role;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Sneat.MVC.Controllers
{
    public class RolesController : BaseController
    {
        [UserAuthenticationFilter]
        public ActionResult Index()
        {
            return View();
        }

        [UserAuthenticationFilter]
        public async Task<PartialViewResult> SearchRole(int page, string search = "")
        {
            var result = await _roleService.SearchRole(page, SystemParam.MAX_ROW_IN_LIST_WEB, search);
            return PartialView("_ListRole", result);
        }
       
        public async Task<int> CreateRole(RoleInputModel input)
        {
            return await _roleService.CreateRole(input);
        }

        public async Task<int> UpdateRole(RoleOutputModel input)
        {
            return await _roleService.UpdateRole(input);
        }

        public async Task<int> RemoveRole(int ID)
        {
            return await _roleService.RemoveRole(ID);
        }

        public async Task<JsonResult> GetAllPermissions()
        {
            var result = await _roleService.GetAllPermissions();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> DetailRole(int ID)
        {
            var result = await _roleService.DetailRole(ID);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

Sneat.MVC/Views/Roles/Index.cshtml
@{
    Layout = "~/Views/Shared/_SneatProLayout.cshtml";
    ViewData["title"] = "Role management";
}
@using Sneat.MVC.Models.DTO.User
@using Sneat.MVC.Common
@{ UserDetailOutputModel ss = (UserDetailOutputModel)HttpContext.Current.Session[SystemParam.SESSION_LOGIN];
    if (ss == null)
    {
        Response.Redirect("/Home/Login");
    }
}

<div class="content-wrapper">
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="py-3 mb-4"><span class="text-muted fw-light" @*data-i18n="User"*@>Quản lý tài khoản /</span> Phân quyền</h4>

        <div class="card">
            <h5 class="card-header" @*data-i18n="User"*@>Danh sách vai trò</h5>
            <div class="row mb-2  px-md-4 px-2">
                <div class="col-md-4 offset-md-0">
                    <div class="input-group input-group-merge">
                        <span class="input-group-text" id="basic-addon-search31"><i class="bx bx-search"></i></span>
                        <input type="text" class="form-control " id="txt-key-search" placeholder="Tên vai trò" onchange="searchRole()" />
                    </div>
                </div>

            </div>
            <div class="row mb-2 px-md-4 px-2">
                <div class="col-md-12 mb-2">
                    @if (ss.PermissionTabs.Contains("createRoleTab"))
                    {
                        <button type="button"
                                class="btn btn-primary"
                                data-bs-toggle="modal"
                                data-bs-target="#addRoleModal"
                                style="float: right">
                            <i class='menu-icon tf-icons bx bx-plus'></i>
                            Thêm mới
                        </button>
                    }

                    @*<button class="btn btn-primary" id="shepherd-example">Start tour</button>*@
                </div>
            </div>

            @if (ss.PermissionTabs.Contains("viewRoleTab"))
            {
                <div class=" table-responsive px-md-4 px-2" id="list_role">
                    @{ Html.RenderAction("SearchRole", "Roles", new { Page = 1, search = "" }); }
                </div>
            }
                
        </div>

    </div>

    <div class="content-backdrop fade"></div>
</div>

<!--modal add Role-->
<div class="modal fade" id="addRoleModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel4">Tạo mới vai trò</h5>
                <button type="button"
                        class="btn-close"
                        data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row col-md-12 col-12">
                    <div class="card mb-md-0 mb-4 col-md-6 col-6">
                        <h5 class="card-header">Thông tin</h5>
                        <div class="card-body">
                            <div class="mb-3">
                                <strong>Tên vai trò</strong><span style="color:red"> *</span>
                                <input type="text" class="form-control" id="nameCreate" name="name" required placeholder="Tên vai trò">
                            </div>
                            <div class="mb-3">
                                <strong>Mô tả</strong>
                                <textarea class="form-control" id="txtDescription" rows="2" placeholder="Mô tả chi tiết..."></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-md-0 mb-4 col-md-6 col-6">
                        <h5 class="card-header">Phân quyền</h5>
                        <div class="card-body">
                            <div id="tree-role"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-label-secondary" data-bs-dismiss="modal">
                    Đóng
                </button>
                <button type="button" onclick="saveCreateRole();" class="btn btn-primary"><i class='menu-icon tf-icons bx bx-plus'></i> Lưu</button>
            </div>
        </div>
    </div>
</div>

<!--modal update Role-->
<div class="modal fade" id="updateRoleModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel4">Cập nhật vai trò</h5>
                <button type="button"
                        class="btn-close"
                        data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row col-md-12 col-12">
                    <div class="card mb-md-0 mb-4 col-md-6 col-6">
                        <h5 class="card-header">Thông tin</h5>
                        <div class="card-body">
                            <div class="mb-3">
                                <input type="hidden" id="roleID" />
                                <strong>Tên vai trò</strong><span style="color:red"> *</span>
                                <input type="text" class="form-control" id="nameEdit" name="name" required placeholder="Tên vai trò">
                            </div>
                            <div class="mb-3">
                                <strong>Mô tả</strong>
                                <textarea class="form-control" id="txtDescriptionEdit" rows="2" placeholder="Mô tả chi tiết..."></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-md-0 mb-4 col-md-6 col-6">
                        <h5 class="card-header">Phân quyền</h5>
                        <div class="card-body">
                            <div id="update-tree-role"></div>
                            <input type="hidden" id="listPermissonIds" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-label-secondary" data-bs-dismiss="modal">
                    Đóng
                </button>
                <button type="button" onclick="saveUpdateRole();" class="btn btn-primary"><i class='menu-icon tf-icons bx bx-plus'></i> Lưu</button>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
@Scripts.Render("~/Scripts/ScriptModel/permission-scipt.js")
@Scripts.Render("~/Scripts/ScriptModel/role-script.js")

Sneat.MVC/Views/Roles/_ListRole.cshtml
@using Sneat.MVC.Models.DTO.Role;
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<RoleOutputModel>
@using Sneat.MVC.Models.DTO.User
@using Sneat.MVC.Common
@{ UserDetailOutputModel ss = (UserDetailOutputModel)HttpContext.Current.Session[SystemParam.SESSION_LOGIN];
    if (ss == null)
    {
        Response.Redirect("/Home/Login");
    }
}

<table class="table table-bordered table-striped text-center" id="dataTable" cellspacing="0">
    <thead>
        <tr>
            <th>STT</th>
            <th>Tên </th>
            <th>Người dùng</th>
            <th>Ngày tạo</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>

        @{
            if (Model.Count() <= 0)
            {
                <tr>
                    <td colspan="8">Không có dữ liệu.</td>
                </tr>
            }
            else
            {

                int stt = ((Model.PageNumber - 1) * Model.PageSize) + 1;
                foreach (var data in Model)
                {

                    <tr>
                        <td>@stt </td>
                        <td>@data.Name</td>
                        <td>
                            <div class="d-flex align-items-center avatar-group">
                                @foreach (var user in data.UserRoles)
                                {
                                    <div class="avatar pull-up"
                                         data-bs-toggle="tooltip"
                                         data-popup="tooltip-custom"
                                         data-bs-placement="top"
                                         title="@user.UserName">
                                        <img src="@user.UserAvatar" alt="Avatar" class="rounded-circle" />
                                    </div>
                                }
                            </div>


                        </td>
                        <td>@data.CreatedDate.ToString("dd/MM/yyyy")</td>
                        <td>
                            <div class="dropdown">
                                <button type="button"
                                        class="btn p-0 dropdown-toggle hide-arrow"
                                        data-bs-toggle="dropdown">
                                    <i class="bx bx-dots-vertical-rounded"></i>
                                </button>
                                <div class="dropdown-menu">
                                    @if (ss.PermissionTabs.Contains("updateRoleTab"))
                                    {
                                        <a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#updateRoleModal" onclick="updateRoleModal(@data.ID)"><i class="bx bx-edit-alt me-1"></i> Sửa vai trò</a>
                                    }
                                    @if (ss.PermissionTabs.Contains("deleteRoleTab"))
                                    {
                                        <a class="dropdown-item" onclick="deleteRole(@data.ID)"><i class="bx bx-trash me-1"></i> Xóa vai trò</a>
                                    }

                                </div>
                            </div>
                        </td>
                    </tr>
                    stt++;

                }
            }
        }

    </tbody>
</table>
<div class="col-md-12">
    <div class="row float-right">
        @*phân trang*@
        @Html.PagedListPager(Model, Page => Url.Action("SearchRole", new { Page, search = "" }),
                 PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions()
                 {
                     HttpMethod = "GET",
                     UpdateTargetId = "list_role"
                 })
                 )
    </div>
</div>