Sneat.MVC/Models/DTO/User/UserDetailOutputModel.cs
using Sneat.MVC.Common;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace Sneat.MVC.Models.DTO.User
{
    public class UserDetailOutputModel
    {
        public int ID { get; set; }
        public int? Status { get; set; }
        public string UserName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Token { get; set; }
        public string Avatar { get; set; }
        public DateTime? CreateDate { set; get; }
        public string CreateDateStr
        {
            set { }
            get
            {
                return CreateDate.HasValue ? CreateDate.Value.ToString(SystemParam.CONVERT_DATETIME) : "";
            }
        }
        public DateTime? Dob { get; set; }
        public string DobSTR
        {
            get
            {
                return Dob.HasValue ? Dob.Value.ToString(SystemParam.CONVERT_DATETIME) : "";
            }
        }
        public int IsDeleted { get; set; }
        public int? Sex { get; set; }
        public int? ProvinceID { get; set; }
        public int? DistrictID { get; set; }
        public string StatusStr
        {
            get
            {
                switch (Status)
                {
                    case SystemParam.ACTIVE:
                        return SystemParam.STATUS_ACTIVE_STR;
                    case SystemParam.IN_ACTIVE:
                        return SystemParam.STATUS_IN_ACTIVE_STR;
                    default:
                        return "Undefined Status";
                }
            }
        }
        public List<string> PermissionTabs { get; set; }
        public List<TeamUserOutputModel> UserTeams { get; set; }
        public List<ProjectUserOutputModel> ListProjects { get; set; }
        public int TotalProjects { get; set; }
    }

    public class TeamUserOutputModel
    {
        public int UserID { get; set; }
        public int TeamID { get; set; }
        public string TeamName { get; set; }
    }

    public class ProjectUserOutputModel
    {
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
    }
}

Sneat.MVC/Models/DTO/User/UserInputModel.cs
using Sneat.MVC.Common;
using Sneat.MVC.Models.Enum;
using System;
using System.Collections.Generic;
namespace Sneat.MVC.Models.DTO.User
{
    public class UserInputModel
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Avatar { get; set; }
        public List<int> RoleIds { get; set; }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime? DOB { get; set; }
        public Gender Gender { get; set; }

        public string Identity { get; set; }
        public DateTime? IdentityReceivedDate { get; set; }
        public string IdentityReceivedPlace { get; set; }
        public string IdentityImages { get; set; }

        public string BankBin { get; set; }
        public string BankAccountName { get; set; }
        public string BankAccountNo { get; set; }
        public string BankQRImage { get; set; }
        public int? ProvinceHomeID { get; set; }

        public int? DistrictHomeID { get; set; }
        public string HomeAddress { get; set; }

        public int? ProvinceOfficeID { get; set; }
        public int? DistrictOfficeID { get; set; }
        public string OfficeAddress { get; set; }

        public int Status { get; set; }
    }

    public class UpdateUserInputModel : UserInputModel
    {
        public int ID { get; set; }
        public DateTime CreateDate { get; set; }
        public string IdentityReceivedDateStr 
        {
            get
            {
                if (IdentityReceivedDate != null)
                    return IdentityReceivedDate.Value.ToString(SystemParam.CONVERT_DATETIME_DATE_PICKER_BASIC);
                else
                    return null;
            }
        }
        public string DOBStr
        {
            get
            {
                if (DOB != null)
                    return DOB.Value.ToString(SystemParam.CONVERT_DATETIME_DATE_PICKER_BASIC);
                else
                    return null;
            }
        }

        public string StatusStr
        {
            get
            {
                switch (Status)
                {
                    case SystemParam.ACTIVE:
                        return SystemParam.STATUS_ACTIVE_STR;
                    case SystemParam.IN_ACTIVE:
                        return SystemParam.STATUS_IN_ACTIVE_STR;
                    default:
                        return "Undefined Status";
                }
            }
        }

        public List<string> PermissionTabs { get; set; }
        public List<TeamUserOutputModel> UserTeams { get; set; }
        public List<ProjectUserOutputModel> ListProjects { get; set; }
        public int TotalProjects { get; set; }
        public string Token { get; set; }
    }
}

Sneat.MVC/Models/Entity/User.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Sneat.MVC.Models.Enum;
using System.Collections.Generic;

namespace Sneat.MVC.Models.Entity
{
    public class User
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Avatar { get; set; }
        public int IsDeleted { get; set; }
        public string Token { get; set; }
        public Status? Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<UserTeam> UserTeams { get; set; }
        public virtual ICollection<UserProject> UserProjects { get; set; }
        public virtual ICollection<UserWorkPackage> UserWorkPackages { get; set; }
    }
}

Sneat.MVC/Controllers/API/UsersController.cs
using Sneat.MVC.Common;
using Sneat.MVC.DAL;
using Sneat.MVC.Models.APIModel;
using Sneat.MVC.Models.DTO.User;
using Sneat.MVC.Models.Entity;
using Sneat.MVC.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using System.Web.Http.Results;

namespace Sneat.MVC.Controllers.API
{
    public class UsersController : ApiController
    {
        protected SneatContext Context;
        public UserService _userService;
        public AuthenticationService _authenticationService;
        public ResponseService _responseService;

        public SneatContext GetContext()
        {
            if (Context == null)
            {
                Context = new SneatContext();
            }
            return Context;
        }

        public UsersController()
        {
            _userService = new UserService(this.GetContext());
            _responseService = new ResponseService();
            _authenticationService = new AuthenticationService(this.GetContext());
        }

        [HttpGet]
        public async Task<JsonResultModel> GetListUserPaging(int page = SystemParam.PAGE_DEFAULT, int limit = SystemParam.MAX_ROW_IN_LIST_WEB, string search = "", string teamIDs = null, int? projectID = null)
        {
            try
            {
                var listPaging = _userService.Search(page, limit, search, projectID, teamIDs);
                var paging = new PagingModel
                {
                    Page = page,
                    Limit = limit,
                    TotalItemCount = listPaging.TotalItemCount,
                };

                return _responseService.SuccessPaging(SystemParam.MESSAGE_SUCCESS, listPaging, paging);
            }
            catch (Exception ex)
            {
                ex.ToString();
                return _responseService.serverError();
            }
        }

        [HttpPost]
        public async Task<JsonResultModel> CreateUser(UserInputModel input)
        {
            var result = await _userService.CreateUser(input);
            if (result == SystemParam.EMAIL_USED_ERR)
                return _responseService.ErrorResult(SystemParam.EMAIL_USED_ERR_STR, SystemParam.SERVER_ERROR_CODE);
            else if (result == SystemParam.PHONE_USED_ERR)
                return _responseService.ErrorResult(SystemParam.PHONE_USED_ERR_STR, SystemParam.SERVER_ERROR_CODE);
            else if (result == SystemParam.RETURN_TRUE)
                return _responseService.SuccessResult(SystemParam.MESSAGE_SUCCESS, result);
            else
                return _responseService.serverError();
        }

        [HttpGet]
        public async Task<JsonResultModel> DetailUser(int ID)
        {
            var result = await _userService.DetailUser(ID);
            return _responseService.SuccessResult(SystemParam.MESSAGE_SUCCESS, result);
        }

        [HttpPost]
        public async Task<JsonResultModel> UpdateUser(UpdateUserInputModel input)
        {
            var result = await _userService.UpdateUser(input);
            if (result == SystemParam.EMAIL_USED_ERR)
                return _responseService.ErrorResult(SystemParam.EMAIL_USED_ERR_STR, SystemParam.SERVER_ERROR_CODE);
            else if (result == SystemParam.PHONE_USED_ERR)
                return _responseService.ErrorResult(SystemParam.PHONE_USED_ERR_STR, SystemParam.SERVER_ERROR_CODE);
            else if (result == SystemParam.ACCOUNT_NOT_FOUND_ERR)
                return _responseService.ErrorResult(SystemParam.ACCOUNT_NOT_FOUND_ERR_STR, SystemParam.SERVER_ERROR_CODE);
            else if (result == SystemParam.RETURN_TRUE)
                return _responseService.SuccessResult(SystemParam.MESSAGE_SUCCESS, result);
            else
                return _responseService.serverError();
        }

        [HttpPost]
        public async Task<JsonResultModel> DeleteUser(int ID)
        {
            var result = await _userService.DeleteUser(ID);
            if (result == SystemParam.ACCOUNT_NOT_FOUND_ERR)
                return _responseService.ErrorResult(SystemParam.ACCOUNT_NOT_FOUND_ERR_STR, SystemParam.SERVER_ERROR_CODE);
            else if (result == SystemParam.RETURN_TRUE)
                return _responseService.SuccessResult(SystemParam.MESSAGE_SUCCESS, result);
            else
                return _responseService.serverError();
        }

        [HttpPost]
        public async Task<JsonResultModel> DeactiveUser(int ID)
        {
            var result = await _userService.ChangeUserStatus(ID, SystemParam.IN_ACTIVE);
            if (result == SystemParam.ACCOUNT_NOT_FOUND_ERR)
                return _responseService.ErrorResult(SystemParam.ACCOUNT_NOT_FOUND_ERR_STR, SystemParam.SERVER_ERROR_CODE);
            else if (result == SystemParam.RETURN_TRUE)
                return _responseService.SuccessResult(SystemParam.MESSAGE_SUCCESS, result);
            else
                return _responseService.serverError();
        }

        [HttpPost]
        public async Task<JsonResultModel> ActivateUser(int ID)
        {
            var result = await _userService.ChangeUserStatus(ID, SystemParam.ACTIVE);
            if (result == SystemParam.ACCOUNT_NOT_FOUND_ERR)
                return _responseService.ErrorResult(SystemParam.ACCOUNT_NOT_FOUND_ERR_STR, SystemParam.SERVER_ERROR_CODE);
            else if (result == SystemParam.RETURN_TRUE)
                return _responseService.SuccessResult(SystemParam.MESSAGE_SUCCESS, result);
            else
                return _responseService.serverError();
        }

        [HttpPost]
        public async Task<JsonResultModel> ChangePassword(int ID, string currentPass, string newPass)
        {
            var result = await _authenticationService.ChangePassword(ID, currentPass, newPass);
            if (result == SystemParam.INVALID_PASSWORD_ERR)
                return _responseService.ErrorResult(SystemParam.INVALID_PASSWORD_ERR_STR, SystemParam.SERVER_ERROR_CODE);
            else if (result == SystemParam.RETURN_TRUE)
                return _responseService.SuccessResult(SystemParam.MESSAGE_SUCCESS, result);
            else
                return _responseService.serverError();
        }
    }
}

Sneat.MVC/Controllers/UsersController.cs
using Sneat.MVC.App_Start;
using Sneat.MVC.Common;
using Sneat.MVC.Models.DTO.User;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Sneat.MVC.Controllers
{
    public class UsersController : BaseController
    {
        [UserAuthenticationFilter]
        public async Task<ActionResult> Index()
        {
            ViewBag.ListTeams = await _teamService.GetListTeam();
            return View();
        }

        [UserAuthenticationFilter]
        public PartialViewResult Search(int page, int limit = SystemParam.MAX_ROW_IN_LIST_WEB, string search = "", int? teamID = null)
        {
            var result = _userService.Search(page, limit, search, teamID);
            return PartialView("_ListUser", result);
        }

        [UserAuthenticationFilter]
        public async Task<ActionResult> Create()
        {
            ViewBag.ListProvince = await _addressService.ListProvince();
            ViewBag.ListBank =  _bankService.GetListBanks();
            ViewBag.ListRole = await _roleService.ListRoleAuthorization();
            return View();
        }

        [HttpPost]
        public async Task<int> CreateUser(UserInputModel input)
        {
            UserDetailOutputModel userLogin = UserLogins;
            return await _userService.CreateUser(input);
        }

        [UserAuthenticationFilter]
        [HttpGet]
        public async Task<ActionResult> Update(int ID)
        {
            ViewBag.ListProvince = await _addressService.ListProvince();
            ViewBag.ListBank = _bankService.GetListBanks();
            ViewBag.ListRole = await _roleService.ListRoleAuthorization();
            var userDetail = await _userService.DetailUser(ID);
            return View(userDetail);
        }

        [UserAuthenticationFilter]
        [HttpGet]
        public async Task<ActionResult> UserProfile(int? ID)
        {
            var userDetail = await _userService.DetailUser((int)ID);
            return View(userDetail);
        }

        [HttpPost]
        public async Task<int> UpdateUser(UpdateUserInputModel input)
        {
            return await _userService.UpdateUser(input);
        }

        [HttpPost]
        public async Task<int> DeleteUser(int ID)
        {
            return await _userService.DeleteUser(ID);
        }

        [HttpPost]
        public async Task<int> DeactiveUser(int ID)
        {
            return await _userService.ChangeUserStatus(ID, SystemParam.IN_ACTIVE);
        }

        [HttpPost]
        public async Task<int> ActivateUser(int ID)
        {
            return await _userService.ChangeUserStatus(ID, SystemParam.ACTIVE);
        }

        [HttpPost]
        public async Task<int> ChangePassword(string currentPass, string newPass)
        {
            UserDetailOutputModel userLogin = UserLogins;
            return await _authenticationService.ChangePassword(userLogin.ID, currentPass, newPass);
        }

    }
}

Sneat.MVC/Views/Users/Index.cshtml
@{
    Layout = "~/Views/Shared/_SneatProLayout.cshtml";
    ViewData["title"] = "User management";
}
@using Sneat.MVC.Models.DTO.User
@using Sneat.MVC.Common
@{ UserDetailOutputModel ss = (UserDetailOutputModel)HttpContext.Current.Session[SystemParam.SESSION_LOGIN];
    if (ss == null)
    {
        Response.Redirect("/Home/Login");
    }
}
<div class="content-wrapper">
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="py-3 mb-4"><span class="text-muted fw-light" @*data-i18n="User"*@>Quản lý tài khoản /</span> Tài khoản</h4>

        <div class="card">
            <h5 class="card-header" @*data-i18n="User"*@>Danh sách tài khoản</h5>
            <div class="row mb-2  px-md-4 px-2">
                <div class="col-md-4 offset-md-0">
                    <div class="input-group input-group-merge">
                        <span class="input-group-text" id="basic-addon-search31"><i class="bx bx-search"></i></span>
                        <input type="text" class="form-control " id="txt-key-search" placeholder="Tên tài khoản, số điện thoại, email" onchange="searchUser()" />
                    </div>
                </div>
                <div class="col-md-4 offset-md-0">
                    <select id="slTeam" class="select2 form-select form-select-lg" data-allow-clear="true" onchange="searchUser()">
                        <option value="">--- Đội nhóm ---</option>
                        @foreach (var team in ViewBag.ListTeams)
                        {
                            <option value="@team.ID">@team.Name</option>
                        }
                    </select>
                </div>
            </div>
            <div class="row mb-2 px-md-4 px-2">
                <div class="col-md-12">
                    <!-- Use col-md-12 and text-md-right -->
                    @if (ss.PermissionTabs.Contains("createUserTab"))
                    {
                        <a title="Thêm tài khoản" style="float: right" class="btn btn-primary" href="/Users/Create">
                            <i class='menu-icon tf-icons bx bx-user-plus'></i>
                            Thêm mới
                        </a>
                    }

                </div>
            </div>

            @if (ss.PermissionTabs.Contains("viewUserTab"))
            {
                <div class=" table-responsive px-md-4 px-2" id="list_user">
                    @{ Html.RenderAction("Search", "Users", new { Page = 1, search = "" }); }
                </div>
            }

        </div>

    </div>

    <div class="content-backdrop fade"></div>
</div>

<script src="~/Scripts/ScriptModel/user-script.js"></script>

Sneat.MVC/Views/Users/_ListUser.cshtml
@using Sneat.MVC.Models.DTO.User;
@using PagedList;
@using PagedList.Mvc;
@using Sneat.MVC.Common
@using Sneat.MVC.Models.Enum
@model IPagedList<UserDetailOutputModel>
@{ UserDetailOutputModel ss = (UserDetailOutputModel)HttpContext.Current.Session[SystemParam.SESSION_LOGIN];
    if (ss == null)
    {
        Response.Redirect("/Home/Login");
    }
}

<table class="table table-bordered table-striped text-center" id="dataTable" cellspacing="0">
    <thead>
        <tr>
            <th>STT</th>
            <th>Avatar</th>
            <th>Tài khoản </th>
            <th>Số điện thoại</th>
            <th>Email</th>
            <th>Trạng thái</th>
            <th>Đội nhóm</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>

        @{
            if (Model.Count() <= 0)
            {
                <tr>
                    <td colspan="8">Không có dữ liệu.</td>
                </tr>
            }
            else
            {

                int stt = ((Model.PageNumber - 1) * Model.PageSize) + 1;
                foreach (var data in Model)
                {

                    <tr>
                        <td>@stt </td>
                        <td>
                            <div class="avatar avatar-md me-2 avatar-online">
                                <img src="@data.Avatar" alt="Avatar" class="rounded" />
                            </div>
                        </td>
                        <td>
                            @data.UserName
                        </td>
                        <td>@data.Phone </td>
                        <td>@data.Email</td>
                        @if (data.Status == SystemParam.ACTIVE)
                        {
                            <td style="font-size: 13px"><span class="badge bg-label-success me-1">@data.StatusStr</span></td>
                        }
                        else if (data.Status == SystemParam.IN_ACTIVE)
                        {
                            <td style="font-size: 13px"><span class="badge bg-label-danger me-1">@data.StatusStr</span></td>
                        }
                        <td>
                            @foreach (var team in data.UserTeams)
                            {
                                <span class="badge bg-label-primary mb-1">@team.TeamName</span>
                            }

                        </td>
                        <td>
                            <div class="dropdown">
                                <button type="button"
                                        class="btn p-0 dropdown-toggle hide-arrow"
                                        data-bs-toggle="dropdown">
                                    <i class="bx bx-dots-vertical-rounded"></i>
                                </button>
                                <div class="dropdown-menu">
                                    @if (ss.PermissionTabs.Contains("updateInfoUserTab") || ss.PermissionTabs.Contains("updateStatusUserTab"))
                                    {
                                        <a class="dropdown-item" onclick="updateUser(@data.ID)"><i class="bx bx-edit-alt me-1"></i> Sửa tài khoản</a>
                                    }
                                    @if (ss.PermissionTabs.Contains("deleteUserTab"))
                                    {
                                        <a class="dropdown-item" onclick="deleteUser(@data.ID)"><i class="bx bx-trash me-1"></i> Xóa tài khoản</a>
                                    }

                                </div>
                            </div>
                        </td>
                    </tr>
                    stt++;

                }
            }
        }

    </tbody>
</table>
<div class="col-md-12">
    <div class="row float-right">
        @*phân trang*@
        @Html.PagedListPager(Model, Page => Url.Action("Search", new { Page, search = "" }),
                 PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions()
                 {
                     HttpMethod = "GET",
                     UpdateTargetId = "list_user"
                 })
                 )
    </div>
</div>

<script>

    function updateUser(id) {
        window.location.assign("/Users/Update?ID=" + id);
    }
</script>